// server-svelte/src/lib/components/user-menu.svelte
<script lang="ts">
  import { authClient } from "$lib/auth-client";
  import { Button } from "$lib/components/ui";
  import ChevronDown from "lucide-svelte/icons/chevron-down";
  import LogOut from "lucide-svelte/icons/log-out";
  import Settings from "lucide-svelte/icons/settings";
  import LayoutGrid from "lucide-svelte/icons/layout-grid";

  interface Props {
    user: {
      name: string | null;
      email: string;
      image: string | null;
    };
  }

  let { user }: Props = $props();

  let isOpen = $state(false);

  let initials = $derived(
    user.name
      ?.split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase() || user.email[0].toUpperCase()
  );

  function handleSignOut() {
    authClient.signOut({
      fetchOptions: {
        onSuccess: () => {
          window.location.href = "/";
        },
      },
    });
  }

  function handleClickOutside(event: MouseEvent) {
    const target = event.target as HTMLElement;
    if (!target.closest(".user-menu")) {
      isOpen = false;
    }
  }
</script>

<svelte:window onclick={handleClickOutside} />

<div class="relative user-menu">
  <Button
    variant="ghost"
    class="relative h-8 w-8 rounded-full p-0"
    onclick={() => (isOpen = !isOpen)}
  >
    {#if user.image}
      <img
        src={user.image}
        alt={user.name || ""}
        class="h-8 w-8 rounded-full object-cover"
      />
    {:else}
      <div class="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-sm font-medium">
        {initials}
      </div>
    {/if}
  </Button>

  {#if isOpen}
    <div class="absolute right-0 mt-2 w-56 rounded-md border bg-popover p-1 shadow-lg z-50">
      <div class="px-2 py-1.5">
        <p class="text-sm font-medium">{user.name}</p>
        <p class="text-xs text-muted-foreground">{user.email}</p>
      </div>
      <div class="my-1 h-px bg-border"></div>
      <a
        href="/workspaces"
        class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"
        onclick={() => (isOpen = false)}
      >
        <LayoutGrid class="h-4 w-4" />
        Workspaces
      </a>
      <a
        href="/settings"
        class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"
        onclick={() => (isOpen = false)}
      >
        <Settings class="h-4 w-4" />
        Settings
      </a>
      <div class="my-1 h-px bg-border"></div>
      <button
        class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"
        onclick={handleSignOut}
      >
        <LogOut class="h-4 w-4" />
        Sign out
      </button>
    </div>
  {/if}
</div>

// server/src/components/auth/user-menu.tsx
"use client";

import { authClient, useSession } from "@/lib/auth-client";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { LinkButton } from "@/components/ui/link-button";
import Link from "next/link";

export function UserMenu() {
  const { data: session, isPending } = useSession();

  if (isPending) {
    return (
      <div className="h-8 w-8" />
    );
  }

  if (!session) {
    return (
      <LinkButton variant="outline" size="sm" href="/login">
        Sign In
      </LinkButton>
    );
  }

  const initials = session.user.name
    ?.split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase() || session.user.email[0].toUpperCase();

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="relative h-8 w-8 rounded-full cursor-pointer">
          <Avatar className="h-8 w-8">
            <AvatarImage src={session.user.image || undefined} alt={session.user.name || ""} />
            <AvatarFallback>{initials}</AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56" align="end" forceMount>
        <DropdownMenuLabel className="font-normal">
          <div className="flex flex-col space-y-1">
            <p className="text-sm font-medium leading-none">{session.user.name}</p>
            <p className="text-xs leading-none text-muted-foreground">
              {session.user.email}
            </p>
          </div>
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem asChild>
          <Link href="/workspaces">Workspaces</Link>
        </DropdownMenuItem>
        <DropdownMenuItem asChild>
          <Link href="/settings">Settings</Link>
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          className="cursor-pointer"
          onClick={() => authClient.signOut({ fetchOptions: { onSuccess: () => { window.location.href = "/" } } })}
        >
          Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
